import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { getSession } from "next-auth/react";
import Login from "@/components/Login";
import Feed from "@/components/Feed";
import RightSidebar from "@/components/RightSidebar";
import axios from "axios";
import React, { useEffect } from "react";







/**
 * The Home page of the Northeastern Social Network.
 * It includes the Header, Sidebar, Feed, and RightSidebar components.
 * If the user is not logged in, it displays the Login component.
 *
 * @param {{ session: Object }} props - Props received from getServerSideProps, including the session data.
 */
export default function Home({ session }) {
    // If the user is not logged in, display the login screen
    if (!session) return <Login />;
    {
        const NEU_SOCIAL_NETWORK_ENDPOINT = "https://neu-social-service-6dff5aa08698.herokuapp.com//api/login";
        const timestamp = new Date().toISOString();
        console.log(session.user.name + " Login timestamp:", timestamp);
        const userData = {
            username: session.user.name,
            loginTimeStamp: timestamp
        };
        console.log(userData);
        axios
            .post(NEU_SOCIAL_NETWORK_ENDPOINT, userData, {
                headers: { "Accept": "application/json",
                    'Content-Type': 'application/json'},
            })
            .then((response) => {
                console.log("login info has been saved");
            })
            .catch((error) => {
                console.error(error);
            });
    }
    return (
        <div>
            {/* Page Head with meta tags and title */}
            <Head>
                <title>Northeastern Social Network</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header of the page */}
            <Header />

            {/* Main content area */}
            <main className="flex bg-gray-100">
                {/* Sidebar component */}
                <Sidebar />
                {/* Feed component */}
                <Feed />
                {/* Right Sidebar component */}
                <RightSidebar />
            </main>
        </div>
    );
}

/**
 * getServerSideProps fetches session data server-side and passes it as props to the page.
 *
 * @param {Object} context - Context object provided by Next.js.
 * @returns {{ props: { session: Object }}} - Props including session data.
 */
export async function getServerSideProps(context) {
    // Fetch session data
    const session = await getSession(context);

    // Return the session data as props
    return {
        props: {
            session,
        },
    };
}
